### ISSUE TITLE
[BUG] Padding glitch

### ISSUE THREAD

**Issue by AirOne01** [Julien-cpsn/ATAC#1]
Cli tooling and help menu not displaying properly: 

[![asciicast](https://asciinema.org/a/16CZ0Hn0f6ap3409wESF1JTUB.svg)](https://asciinema.org/a/16CZ0Hn0f6ap3409wESF1JTUB)

Got the same result from cloning and running `cargo run` and downloading the binary executable and running it directly.

Using:
- Arch Linux
- `x86_64`
- [kitty terminal](https://sw.kovidgoyal.net/kitty/)
- [fish shell](https://fishshell.com/)
- And the prompt is [starship](https://starship.rs/)

Hit me up for details :+1:

**Comment by Julien-cpsn** [comment]
Thanks for your precious feedback!

The bug should have been fixed in https://github.com/Julien-cpsn/ATAC/releases/tag/v0.6.1 , waiting for your feedback

**Comment by AirOne01** [comment]
Yup, it's fixed. Closing now
