### ISSUE TITLE
ATAC crashes on request parameter deletion

### ISSUE THREAD

**Issue by moimo97** [Julien-cpsn/ATAC#110]
<h2>Issue</h2>
I've noticed that when you try to delete a request parameter ATAC crashes due to an out of bound access on a vect.
<h2>Step to reproduce the issue</h2>
<ol>
<li>Create a collection</li>
<li>Create a request (I used a GET request)</li>
<li>Create a parameter for the request</li>
<li>Delete the created parameter</li>
</ol>
<h2>Solution</h2>
I have inspected the code and found that the issue is on line 58 of file src/tui/tui_logic/request/query_params.rs.
<code>match self.delete_query_param(selection.0, selected_request_index.0, selected_request_index.1) {</code>
Here the first parameter of the function code is the selected parameter row. But from the function definition is clear that it should be the last (3rd) parameter.
<code>pub fn delete_query_param(&mut self, collection_index: usize, request_index: usize, row: usize) -> anyhow::Result<()> {</code>

I have fixed it in my local repository and it solve the issue.

This is the first time I contribute to an open source project, can I simply commit it to the repository?
Hope this is useful,
Good evening

**Comment by Julien-cpsn** [comment]
Fixed in https://github.com/Julien-cpsn/ATAC/commit/e3287f2bec54b8088df7bd55699bc4dc787c5eb9
