### ISSUE TITLE
[BUG] Crash When Deleting Header

### ISSUE THREAD

**Issue by Tahinli** [Julien-cpsn/ATAC#113]
If you try to delete a header lets say user-agent header with 'd' button. You get this error:

thread 'main' panicked at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atac-0.18.0/src/app/business_logic/request/utils.rs:15:60: index out of bounds: the len is 1 but the index is 1

**Comment by Julien-cpsn** [comment]
Fixed in https://github.com/Julien-cpsn/ATAC/commit/e3287f2bec54b8088df7bd55699bc4dc787c5eb9
