### ISSUE TITLE
[ux] selecting creating request without existing collection has no effect

### ISSUE THREAD

**Issue by brandon1024** [Julien-cpsn/ATAC#12]
# Issue Description

If you try to create a new request without having created a collection already, nothing happens when you press enter. This is a bit confusing.

# Possible Solutions

One possible solution would be to create a default collection if this occurs. Maybe a collection with the name `other`.

Another approach could be to show a warning message.

**Comment by Julien-cpsn** [comment]
Now when there are no collections, the popup will only show one choice:

![image](https://github.com/Julien-cpsn/ATAC/assets/64107022/f7fb0fdf-8b1a-4480-84e9-500449aa83c6)

And 2 when at least one collection exists:

![image](https://github.com/Julien-cpsn/ATAC/assets/64107022/488026ec-0a53-4ca9-acf4-0c566d63bfa7)

**Comment by Julien-cpsn** [comment]
Now when there are no collection, it automatically chooses the "collection" option and bring you to the creating collection popup.
Otherwise, nothing changes
