### ISSUE TITLE
Error when running a request

### ISSUE THREAD

**Issue by saitharun14** [Julien-cpsn/ATAC#126]
Hello,

Great work on the tool!!

Running any request on macOS, I'm getting the error "Request error: builder error for url".

I have installed atac from homebrew.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/b55bcd06-bf45-4de8-ac95-d3c3bfa18b30" />

Please let me know if any further details are needed.

Thanks.

**Comment by Julien-cpsn** [comment]
Hi!

I think you forgot the http:// or https://

Have a great day

**Comment by saitharun14** [comment]
Hi! I'm so sorry for that silly question, it was definitely a bit of a brain lapse! Copied the url directly from postman. It's working now. Wishing you all the best for a happy and successful New Year!
