### ISSUE TITLE
Cannot install from AUR - "One or more files did not pass the validity check"

### ISSUE THREAD

**Issue by Sairyss** [Julien-cpsn/ATAC#21]
First of all, great project.

I encountered an issue when installing atac from AUR in arch linux.
Tried both `yay` and `paru`, I get an error:

```
==> Validating source files with sha512sums...
    atac-0.12.0.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: atac-exit status 1
```

Seems like checksum validation fails.

**Comment by Julien-cpsn** [comment]
@orhun I am definitly lacking some knowledge here

**Comment by AlisCode** [comment]
The PKGBUILD maintained by @orhun is not referencing the correct SHA512 sum. This is not an issue with ATAC itself. I suggest the following : 

* Read the [AUR documentation on the Arch Wiki](https://wiki.archlinux.org/title/Arch_User_Repository) to learn how to install an AUR package without an AUR helper.
* Copy the PKGBUILD from Orhun locally, and fix the sha512sums field (see below)
* For reference, the correct sum for the release 0.12.0 is `6fac4c84fa72ceadc4a0076cb761faaf080a53e2c3fb8620bd9ae6bd75da6142562cd7c14190e02acca0f22ac94a1174c03ac726951fb1f15ad85770ef38ff59`. To get that value, get the source as a tar.gz archive from the releases, e.g. https://github.com/Julien-cpsn/ATAC/releases/tag/v0.12.0 and run e.g. `sha512sum ATAC-0.12.0.tar.gz`

**Comment by orhun** [comment]
Yeah, I also couldn't reproduce the issue.

**Comment by Sairyss** [comment]
Package is not even available in AUR anymore https://aur.archlinux.org/pkgbase/atac

**Comment by Julien-cpsn** [comment]
> Package is not even available in AUR anymore https://aur.archlinux.org/pkgbase/atac

It has been move to official Arch repos https://archlinux.org/packages/extra/x86_64/atac

**Comment by Sairyss** [comment]
Installing with pacman works correctly now, closing.
