### ISSUE TITLE
How to send a request?

### ISSUE THREAD

**Issue by ajerni** [Julien-cpsn/ATAC#23]
Looks good and runs in my terminal. I can configure requests, but how can I actually SEND a request?

**Comment by Arjen-Runnr** [comment]
With the space bar. I agree that it's not immediately obvious.

**Comment by Julien-cpsn** [comment]
@ajerni @Arjen-Runnr Firtsly it was with ctrl + enter, but sadly it doesn't register right on some linux-based distributions...

-> https://github.com/crossterm-rs/crossterm/issues/685

**Comment by ajerni** [comment]
runs perfect with space - thanks a lot!
