### ISSUE TITLE
my response body not word wrap 

### ISSUE THREAD

**Issue by ajitirto** [Julien-cpsn/ATAC#27]
i am hit this [https://dummyjson.com/products] but show result respond like this ?
 
{"products":[{"id":1,"title":"iPhone 9","description":"An apple mobile which is nothing like a█

![image](https://github.com/Julien-cpsn/ATAC/assets/22515179/f546020e-ef3f-4100-bcd5-253e9b9e55c6)

**Comment by Julien-cpsn** [comment]
Also, if you change the result tab at least one time (don't ask me why, it's a bug), you will be able to scroll your result with `ctrl + keys`

**Comment by Julien-cpsn** [comment]
Added pretty printer in https://github.com/Julien-cpsn/ATAC/commit/002c7f37d9f7bef3991d387ada4c0d701f9404ce
Will come out in v0.13.0
