### ISSUE TITLE
Add typo spelling GitHub actions

### ISSUE THREAD

**Issue by ccoVeille** [Julien-cpsn/ATAC#28]
I think your project could benefit from existing GitHub actions that check for typos in code, comments and documentation

**Comment by ccoVeille** [comment]
I'm familiar with these tools, I could add them for you.

**Comment by Julien-cpsn** [comment]
Hmm interesting, go forward to make a pull request so that I can check it

**Comment by ccoVeille** [comment]
Sure, can you assign me this issue then, so I can find it back more easily.

**Comment by Julien-cpsn** [comment]
done!
