### ISSUE TITLE
Homebrew integration/tap

### ISSUE THREAD

**Issue by ccoVeille** [Julien-cpsn/ATAC#3]
Do you have any plan to support homebrew install?

It's a convenient way to make your tool available for everyone, and it helps to keep the tool up to date

**Comment by ccoVeille** [comment]
Don't forget how people are lazy 😁

**Comment by Julien-cpsn** [comment]
Hello (again)!
Yes it will be published on homebrew and some other easy-accces packet managers as long as the v1.0.0 comes out (soon I hope)
My first target will simply be cargo, so that you can do something like `cargo install atac`

**Comment by Julien-cpsn** [comment]
Update: you can now install/update it with `cargo install atac`
Link to the crates.io for lazy people: https://crates.io/crates/atac

I'll also try with homebrew, nix and some others

**Comment by Julien-cpsn** [comment]
@ccoVeille ok ok ok
I think I got it to work, but unfortunatly I don't have a mac :(

Can you try it and give me some feedback?

```
brew tap julien-cpsn/atac
brew install atac
```

PS: In case you wonder (which is normal) here is the homebrew repo https://github.com/Julien-cpsn/homebrew-atac

**Comment by Julien-cpsn** [comment]
@ccoVeille I am a noob to brew... Should I put the universal-linux archive or the universal-apple archive into the brew tap?

**Comment by ccoVeille** [comment]
I have never packaged something into brew, I'm unsure I can help.

I would say you have to do both, one for making the program available for Mac users and one for Linux ones

**Comment by Julien-cpsn** [comment]
Ok I think I figured it out!

Delete the previous formula and try this one

```
brew tap julien-cpsn/atac
brew install atac
```

**Comment by ccoVeille** [comment]
It works well. 👍

**Comment by ccoVeille** [comment]
Where is the code you used to package it with homebrew?

**Comment by Julien-cpsn** [comment]
> Where is the code you used to package it with homebrew?

The [atac-x86_64-unknown-linux-musl.tar.gz](https://github.com/Julien-cpsn/ATAC/releases/download/v0.11.2/atac-x86_64-unknown-linux-musl.tar.gz) in https://github.com/Julien-cpsn/ATAC/releases/tag/v0.11.2

**Comment by ccoVeille** [comment]
This is how the binaries are built. My point was more to know where you told brew a tap was available.

I found it

https://github.com/Julien-cpsn/homebrew-atac

**Comment by ccoVeille** [comment]
I'm unsure how you could make this automatic via a GitHub action.

**Comment by Julien-cpsn** [comment]
I think it's possible with a little home-made script that can publish to every platform. Because even if it doesn't seems like, it's a long process to publish a release.

**Comment by ccoVeille** [comment]
I found these

https://github.com/Homebrew/actions
https://til.simonwillison.net/homebrew/auto-formulas-github-actions

**Comment by ccoVeille** [comment]
I confirm it works as expected

```console
$ brew outdated
==> Auto-updated Homebrew!
==> Updated Homebrew from a553f96c96 to d5d380e1f4.
Updated 1 tap (julien-cpsn/atac).

You have 1 outdated formulae installed.

julien-cpsn/atac/atac (0.11.2) < 0.11.3
```

```console
$ brew upgrade atac
==> Upgrading 1 outdated package:
julien-cpsn/atac/atac 0.11.2 -> 0.11.3
==> Fetching julien-cpsn/atac/atac
==> Upgrading julien-cpsn/atac/atac
  0.11.2 -> 0.11.3 
🍺  /home/linuxbrew/.linuxbrew/Cellar/atac/0.11.3: 3 files, 12.8MB, built in 1 second
```

**Comment by Julien-cpsn** [comment]
Incredible
Now I only have to automate it

**Comment by ccoVeille** [comment]
Yes! The famous "just" ™️ and "only"™️, two development buddies that can lead to work a lot to achieve it.
