### ISSUE TITLE
Add headers highlighting

### ISSUE THREAD

**Issue by savchenko** [Julien-cpsn/ATAC#31]
Response body has syntax highlighting. Can something similar be applied to the headers section? At least to differentiate a header from its content.

**Comment by Julien-cpsn** [comment]
Hello,
I am note quite sure I understand. You mean for the response headers?

**Comment by Julien-cpsn** [comment]
@savchenko

**Comment by Julien-cpsn** [comment]
yes sure I'll highligh them more. It will not be displayed as a table like on the request part though

**Comment by Julien-cpsn** [comment]
> > yes sure I'll highlight them more. It will not be displayed as a table like on the request part though
> 
> Any reason not to? Depending on the length of the longest header it might be not the best utilisation of the free space, however in situation with many similar headers is might be handy.

your first reason was the right one. It is hard to implement when considering things like scrolling. And as you said, for long headers it will more annoying so let's keep it simple
