### ISSUE TITLE
Crash try use scroll

### ISSUE THREAD

**Issue by kriollo** [Julien-cpsn/ATAC#32]
thread 'main' panicked at C:\Users\jjara\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ratatui-0.26.2\src\widgets\scrollbar.rs:569:10:─────────────────────────┘
Scrollbar area is emptylt body (301.07ms) │ Cookies │ Headers
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by kriollo** [comment]
This error occurs every time I enter to view the response, scroll, and then press [ESC].


thread 'main' panicked at C:\Users\jjara\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ratatui-0.26.2\src\widgets\scrollbar.rs:569:10:                                               █
Scrollbar area is empty              │                                                                                                                                                     █
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Julien-cpsn** [comment]
Hello!
Can you give me the content of the `atac.log` file, after a run that crashes like you describe pls

Thanks for your feedback

**Comment by kriollo** [comment]
KeyModifiers(0x0)        Enter                    Editing request header                  
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(CONTROL)    Up                       Request menu                            
KeyModifiers(0x0)        Char('v')                Editing request header                  
KeyModifiers(0x0)        Char('v')                Editing request header                  
KeyModifiers(0x0)        Esc                      Editing request header                  
KeyModifiers(0x0)        Char('v')                Request menu

**Comment by kriollo** [comment]
apparently the error occurs when I enter to view the response, at first it doesn’t show the scroll, but if I exit and re-enter, it shows the scroll, and if I exit again, it crashes.
i have windows 11

KeyModifiers(0x0)        Enter                    Main menu                               
KeyModifiers(0x0)        Char('v')                Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(CONTROL)    Down                     Request menu                            
KeyModifiers(0x0)        Esc                      Request menu                            
KeyModifiers(0x0)        Enter                    Main menu                               
KeyModifiers(0x0)        Char('v')                Request menu

**Comment by Julien-cpsn** [comment]
@kriollo have you tried to update from v0.12.0 to v0.13.0 ?

I fixed a lot of issues concerning the views
