### ISSUE TITLE
AUR pkg has been removed?

### ISSUE THREAD

**Issue by Miguerfi** [Julien-cpsn/ATAC#41]
![image](https://github.com/Julien-cpsn/ATAC/assets/91486755/99ff5886-c9fb-4126-b874-dfa8cb866d1b)

**Comment by Julien-cpsn** [comment]
Hello,
Yes it is being replaced onto the official packet manager. I am just waiting for a typo in order to merge the pr

https://archlinux.org/packages/extra/x86_64/atac

**Comment by spaceCabbage** [comment]
uh oh, i just installed it with yay... working fine so far

**Comment by Julien-cpsn** [comment]
Can I close the issue?

**Comment by spaceCabbage** [comment]
```shell
$ ~/atac ❯ yay -S atac
Sync Explicit (1): atac-0.13.0-1
resolving dependencies...
looking for conflicting packages...

Package (1)  New Version  Net Change

extra/atac   0.13.0-1       6.33 MiB

Total Installed Size:  6.33 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                   [--------------------------------------------------------] 100%
(1/1) checking package integrity                                                                 [--------------------------------------------------------] 100%
(1/1) loading package files                                                                      [--------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                [--------------------------------------------------------] 100%
:: Processing package changes...
(1/1) installing atac                                                                            [--------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

``` 

seems to be working fine for me, EndeavorOS

**Comment by spaceCabbage** [comment]
aur page is still missing tho
![Screenshot_20240421_184225](https://github.com/Julien-cpsn/ATAC/assets/85190787/a9654e9f-0a75-464c-9936-10431f3b3783)

**Comment by spaceCabbage** [comment]
lovin this rest client tho, incredible work @Julien-cpsn

**Comment by Julien-cpsn** [comment]
> aur page is still missing tho !

I don't understand, if the package is available in the official Arch packages, why would you need the Aur package to be available?

> lovin this rest client tho, incredible work @Julien-cpsn

Thanks man! Very big updates incomming (today I hope)

**Comment by spaceCabbage** [comment]
that is true, my mistake, 
i went and googled the aur when i saw paru in the readme and ended up just trying yay
