### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by ccoVeille** [Julien-cpsn/ATAC#5]
@Julien-cpsn I see you are pushing commit into main without using PR.

I would like to suggest you to push your code changes in feature branch, then use PR when you want to merge a feature.

I think it would be better because you could get feed back from community, or people may add reference to PR to point bugs or ask question.

Just a suggestion.

https://cli.github.com/ can help you to achieve that.

**Comment by Julien-cpsn** [comment]
Yes sure!
I am working with 1 branch per feature/fix at work. When starting, I wanted to keep it simple in order to focus on the code itself. But since some people like you are willing to contribute (I guess), I'll start working with some more branches soon!
