### ISSUE TITLE
BUG: Error when sending a simple GET request

### ISSUE THREAD

**Issue by idodav** [Julien-cpsn/ATAC#60]
Created a collection and a simple get request to google.
Pressed space to send the request.
And receieved:
index out of bounds: the len is 0 but the index is 0

<img width="1492" alt="Screenshot 2024-05-02 at 23 39 49" src="https://github.com/Julien-cpsn/ATAC/assets/21335259/ad02958d-f20a-4e4c-9b71-faeab457d421">
<img width="1495" alt="Screenshot 2024-05-02 at 23 40 16" src="https://github.com/Julien-cpsn/ATAC/assets/21335259/6c984df8-d924-43d5-ab0c-1fa6dfdb2860">

**Comment by Julien-cpsn** [comment]
Hello @idodav!

Sorry for this dumb bug, it will be fixed with the next release. If you built the app yourself, I encourage you tu use the `60-bug-error-when-sending-a-simple-get-request` branch where the bug is fixed.

Have a great day

**Comment by Julien-cpsn** [comment]
https://github.com/Julien-cpsn/ATAC/releases/tag/v0.15.1
