### ISSUE TITLE
Crash when sending a request (index out of bounds)

### ISSUE THREAD

**Issue by payolin** [Julien-cpsn/ATAC#62]
Steps:
Set ATAC_MAIN_DIR to empty folder ~/.atac
Ran atac, importing a JSON postman file
Issued a request from the config
Upon hitting space, the application crashes with the following message:
```
thread 'main' panicked at src/app/app_logic/environment:12:26
index out of bounds: the len is 0 but the index is 0
```

**Comment by Julien-cpsn** [comment]
Hello, 

it is the same as here https://github.com/Julien-cpsn/ATAC/issues/60

Sorry for this bug, the fix will be in the next release

**Comment by Julien-cpsn** [comment]
https://github.com/Julien-cpsn/ATAC/releases/tag/v0.15.1
