### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by brenoprata10** [Julien-cpsn/ATAC#65]
Hey o/

I am trying to run this http request: 
![image](https://github.com/Julien-cpsn/ATAC/assets/26099427/72a96556-da2a-4027-bd8b-1b6eb2c7d600)

But I keep getting this error:

```thread 'main' panicked at /home/brenoprata/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atac-0.15.0/src/app/app_logic/environment.rs:12:26:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is my PC neofetch

![image](https://github.com/Julien-cpsn/ATAC/assets/26099427/ba731bde-3928-49cd-8fb5-0940318c9dd4)

**Comment by IchbinLuka** [comment]
Having the same problem on Ubuntu without WSL. I have tried a few different URLs and methods and this seems to happen every time. 

This is the full error message in my case. 
```
thread 'main' panicked at /home/[username]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atac-0.15.0/src/app/app_logic/environment.rs:12:26:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Julien-cpsn** [comment]
Hello @IchbinLuka @brenoprata10 

please update to the newest version https://github.com/Julien-cpsn/ATAC/releases/tag/v0.15.1

related to: https://github.com/Julien-cpsn/ATAC/issues/60 https://github.com/Julien-cpsn/ATAC/issues/62

**Comment by brenoprata10** [comment]
It's working great now! 

Great app man!

**Comment by brenoprata10** [comment]
I have donated a small amount to your paypal as a "Thank you gift" 👍

**Comment by Julien-cpsn** [comment]
@brenoprata10 haha I really appreciate, thanks!
