### ISSUE TITLE
Feature Request: use default `directory` if not specified

### ISSUE THREAD

**Issue by namespaceYcZ** [Julien-cpsn/ATAC#68]
Now ATAC (version 0.15.1) must be given a working directory on startup.
![image](https://github.com/Julien-cpsn/ATAC/assets/3965259/8f36fa82-9487-4b12-a906-c5dd63a974d6)

IMHO, a tui application can use the default directory specified by the OS, i.e:
| OS | config directory | cache directory |
| ---- | ---- | ---- |
| Linux | `/home/alice/.config/barapp` | `/home/alice/.cache/barapp` |
| Windows| `C:\Users\Alice\AppData\Roaming\Foo Corp\Bar App\config` | `C:\Users\Alice\AppData\Local\Foo Corp\Bar App\cache` |
| MacOS | `/Users/Alice/Library/Application Support/com.Foo-Corp.Bar-App` | `/Users/Alice/Library/Caches/com.Foo-Corp.Bar-App` |

(Suppose the user name is `Alice`, the organization name is `Foo Corp` and the application name is `Bar App`).

All this can be easily handled by the `directory` crate:

```toml
[dependencies]
directories = "5"
```
```rust
// these are just examples, there must be some other much more better options
// and if you want the `ORGANIZATION` be present on Linux, some thing like `#[cfg(target_os = "linux")]` can be used
pub const APP_NAME: &str = "ATAC";
pub const QUALIFIER: &str = "fr";
pub const ORGANIZATION: &str = "Julien";

let project_dir = directories::ProjectDirs::from(QUALIFIER, ORGANIZATION, APP_NAME).unwrap();
let config_dir = project_dir.config_dir();
let cache_dir = project_dir.cache_dir();
let mut log_dir = cache_dir.to_owned();
log_dir.push("logs");
```

**Comment by namespaceYcZ** [comment]
> > What kind of knowledge do you need? I'm very glad to help but I lack experience and necessary knowledge. I saw some links on the [document page](https://docs.rs/directories/latest/directories/) of the `directories` crate which might help you.
> 
> I do not understand how the directory gets created, does I need to always try to create the directory when using the app ? Or does it needs something specific when installing?
> 
> Will it work with the `ATAC_MAIN_DIR` variable or do I have to change the way it works?
> 
> Thanks in advance

![image](https://github.com/Julien-cpsn/ATAC/assets/3965259/9c8bb47f-9439-44ce-873b-343643cc7be8)
![image](https://github.com/Julien-cpsn/ATAC/assets/3965259/47e77940-421f-4401-8d9f-5e701d0c05e9)

I think the `directories` crate doesn't automatically create the project directory for us. So I suggest that ATAC create it if the `directory` argument was not provided, the `ATAC_MAIN_DIR` env variable was not provided and the project directory was not found.

I draw a flow chart to make it clear:
![未命名文件](https://github.com/Julien-cpsn/ATAC/assets/3965259/f6bef74e-00d5-4a43-859b-91d1fc869c32)

**Comment by ccoVeille** [comment]
> IMHO, a tui application can use the default directory specified by the OS, i.e:\n\nOS\tconfig directory\tcache directory\nLinux\t/home/alice/.config/barapp\t/home/alice/.cache/barapp\nWindows\tC:\\Users\\Alice\\AppData\\Roaming\\Foo Corp\\Bar App\\config\tC:\\Users\\Alice\\AppData\\Local\\Foo Corp\\Bar App\\cache\nMacOS\t/Users/Alice/Library/Application Support/com.Foo-Corp.Bar-App\t/Users/Alice/Library/Caches/com.Foo-Corp.Bar-App\n(Suppose the user name is Alice, the organization name is Foo Corp and the application name is Bar App).\n\nAll this can be easily handled by the directory crate:\n\n[dependencies]\ndirectories = \"5\"\n// these are just examples, there must be some other much more better options\n// and if you want the `ORGANIZATION` be present on Linux, some thing like `#[cfg(target_os = \"linux\")]` can be used\npub const APP_NAME: &str = \"ATAC\";\npub const QUALIFIER: &str = \"fr\";\npub const ORGANIZATION: &str = \"Julien\";\n\nlet project_dir = directories::ProjectDirs::from(QUALIFIER, ORGANIZATION, APP_NAME).unwrap();\nlet config_dir = project_dir.config_dir();\nlet cache_dir = project_dir.cache_dir();\nlet mut log_dir = cache_dir.to_owned();\nlog_dir.push(\"logs\");

Please also consider that in addition of that, people might expect to respect XDG_CONFIG_HOME and XDG_DATA_HOME

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Does this crate respect that?

**Comment by namespaceYcZ** [comment]
> > IMHO, a tui application can use the default directory specified by the OS, i.e:\n\nOS\tconfig directory\tcache directory\nLinux\t/home/alice/.config/barapp\t/home/alice/.cache/barapp\nWindows\tC:\Users\Alice\AppData\Roaming\Foo Corp\Bar App\config\tC:\Users\Alice\AppData\Local\Foo Corp\Bar App\cache\nMacOS\t/Users/Alice/Library/Application Support/com.Foo-Corp.Bar-App\t/Users/Alice/Library/Caches/com.Foo-Corp.Bar-App\n(Suppose the user name is Alice, the organization name is Foo Corp and the application name is Bar App).\n\nAll this can be easily handled by the directory crate:\n\n[dependencies]\ndirectories = "5"\n// these are just examples, there must be some other much more better options\n// and if you want the `ORGANIZATION` be present on Linux, some thing like `#[cfg(target_os = \"linux\")]` can be used\npub const APP_NAME: &str = "ATAC";\npub const QUALIFIER: &str = "fr";\npub const ORGANIZATION: &str = "Julien";\n\nlet project_dir = directories::ProjectDirs::from(QUALIFIER, ORGANIZATION, APP_NAME).unwrap();\nlet config_dir = project_dir.config_dir();\nlet cache_dir = project_dir.cache_dir();\nlet mut log_dir = cache_dir.to_owned();\nlog_dir.push("logs");
> 
> Please also consider that in addition of that, people might expect to respect XDG_CONFIG_HOME and XDG_DATA_HOME
> 
> https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> 
> Does this crate respect that?

I'm not quite sure, maybe it does according to its comment:
![image](https://github.com/Julien-cpsn/ATAC/assets/3965259/e1d663b4-985c-498e-a986-602e16585d6a)
![image](https://github.com/Julien-cpsn/ATAC/assets/3965259/de096ffa-5c13-4434-96d2-37e7ba01bc22)

**Comment by Julien-cpsn** [comment]
Closes by https://github.com/Julien-cpsn/ATAC/releases/tag/v0.18.0
