### ISSUE TITLE
Feature Request: Generate items like UUIDs in headers

### ISSUE THREAD

**Issue by ErkanSensei** [Julien-cpsn/ATAC#81]
There are times where you want to generate a UUID or a timestamp in the header to be able to track a request. Would be nice if we could do {{UUID}} or {{TIMESTAMP}} to automatically generate this and insert it like with env variables.

**Comment by Julien-cpsn** [comment]
hello @ErkanSensei !

This is a very great idea. I'll note that one in the todo list

Have a great day

**Comment by ErkanSensei** [comment]
Wish I could help with these requests but I don't know Rust unfortunately :/ Great project though either way!

**Comment by Julien-cpsn** [comment]
![image](https://github.com/Julien-cpsn/ATAC/assets/64107022/bf7481d3-4a2a-4d9f-ba0a-cb0630d08a5c)

here you go @ErkanSensei

**Comment by Julien-cpsn** [comment]
Closed by https://github.com/Julien-cpsn/ATAC/commit/3d5155241829216b9dc8c38efc759ce4a23edfc3
