### ISSUE TITLE
Feature Request: Cancel a pending request

### ISSUE THREAD

**Issue by ErkanSensei** [Julien-cpsn/ATAC#82]
Forgot to return a response in an endpoint and realized I couldn't cancel the request from ATAC; the only way I was able to was by closing the app and rerunning atac.

**Comment by Julien-cpsn** [comment]
Hello @ErkanSensei !

Yes this might a great thing to implement. I'll give it a try when available to work back on the project
Note that the requests have a 30sec timeout by default.

Have a great day!

**Comment by Julien-cpsn** [comment]
Closed by https://github.com/Julien-cpsn/ATAC/commit/382c3ad75f6cc9e79b69b97b6827b6de8261084d
