### ISSUE TITLE
use config directory instead of env variables

### ISSUE THREAD

**Issue by kayuxx** [Julien-cpsn/ATAC#87]
just a suggestion here, i think it would be great if the config directory `~/.config/atac` can be used instead of env variables

**Comment by Julien-cpsn** [comment]
> just a suggestion here, i think it would be great if the config directory `~/.config/atac` can be used instead of env variables

Hello @kayuxx 

Yes this is something that will be worked on, the default dir will be among other binaries. Although, the env variable will still be accessible in case you want to use another dir

Have a great day

**Comment by Julien-cpsn** [comment]
Closing in favor of https://github.com/Julien-cpsn/ATAC/issues/68
