### ISSUE TITLE
FR: Package as Docker image

### ISSUE THREAD

**Issue by pataquets** [Julien-cpsn/ATAC#96]
Hi there. I've just learnt about ATAC and found it awesome! Thanks for sharing.
Aside from using it myself, I'm thinking of easy ways to bundle ATAC as another tool in software development stacks.
For instance, on a `Makefile`-controlled stack in any repo, you could easily add just a simple `docker run` one-liner to allow users to start ATAC with a local JSON/YAML without requiring them even installing.
Also, projects could just distribute their own custom Docker images with their API definitions baked in, just creating a `Dockerfile` which would use ATAC's public image as base.
No need to mention that you could run ATAC by just issuing a `docker run` command, no install needed.

If maintaining an official public image sounds too much work, an alternative could be just hosting a `Dockerfile` in the repo which in turn would allow a ad-hoc image build with a simple `docker build` from the repo's URL.

Would this be an acceptable feature/PR?

**Comment by Julien-cpsn** [comment]
Hello man!

Adding this feature could be a great thing. But I don't have the time/knowledge to maintain it efficiently. If you are willing to do it, you can be the main referee regarding this feature (like a distro packager)

PR are appreciated :)

Have a great day!!

**Comment by pataquets** [comment]
Great to know! Thanks for considering. 
I'm bookmarking this issue, since as of now I don't have the bandwidth needed to do it. 
However, when the occasion arrives and I get some time "budgeted" to do it, I'm already confident it will be accepted. 
Meanwhile, some other user interested in this might want to pick this up.

For completeness, these are the tasks need here: 
- Crafting a suitable Dockerfile.
- Adding a GitHub Action file which would build and push the image to Docker Hub on each commit/tag/manual/etc.
- Configuring the GitHub Action with a DH account API key for pushing (this is the only task you'll need to do yourself).

What will be needed later (in case you want to have it ready beforehand) is for you to have a Docker Hub account ready (it's free). You might want to grab it now, to ensure you have the desired username and prevent others from taking it before. Other than that, no urgency for now.

**Comment by alan910127** [comment]
Hello, I'm available to implement this feature! 

Regarding the Docker Hub account setup, I can start by creating a GitHub workflow that is initially disabled. Once @Julien-cpsn sets up the Docker Hub account, they can re-enable it, and the workflow will be good to go. Does that sound okay?

**Comment by Julien-cpsn** [comment]
> Hello, I'm available to implement this feature! 
> 
> Regarding the Docker Hub account setup, I can start by creating a GitHub workflow that is initially disabled. Once @Julien-cpsn sets up the Docker Hub account, they can re-enable it, and the workflow will be good to go. Does that sound okay?

Hello,

Yes, go with that!
I'll try to create the DH account today

If you want to speak more in depth about it, come to the app discord :)

Have a great day
