### ISSUE TITLE
error installing with cargo - error[E0308]: mismatched types     

### ISSUE THREAD

**Issue by ket000** [Julien-cpsn/ATAC#97]
Trying to run this on WSL2 Oracle Linux 8.19 with below. Also Cargo and rust version is 1.80. Can not use binary install due to incompatible GLIBC Version. 

cargo install atac gives below error.

error[E0308]: mismatched types
    --> /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atac-0.16.0/src/app/events.rs:665:49
     |
664  |                 EditingRequestBodyStringCharInput(_) => match key {
     |                                                               --- this expression has type `KeyCombination`
665  |                     KeyCombination { codes: One(KeyCode::Char(char)), .. } => self.body_text_area.insert_char(char),
     |                                                 ^^^^^^^^^^^^^^^^^^^ expected `crokey::crossterm::event::KeyCode`, found `ratatui::crossterm::event::KeyCode`
     |
     = note: `ratatui::crossterm::event::KeyCode` and `crokey::crossterm::event::KeyCode` have similar names, but are actually distinct types
note: `ratatui::crossterm::event::KeyCode` is defined in crate `crossterm`
    --> /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crossterm-0.27.0/src/event.rs:841:1

**Comment by rafaelsmgomes** [comment]
Same

**Comment by stormvirux** [comment]
Similar issue, installing with cargo results in E0277, E0308.

```
error[E0277]: the trait bound `ratatui::crossterm::event::KeyEvent: From<KeyCombination>` is not satisfied
   --> /home/thaha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atac-0.16.0/src/utils/vim_emulation.rs:192:53
    |
192 |                     let key_event: KeyEvent = input.into();
    |                                                     ^^^^ the trait `From<KeyCombination>` is not implemented for `ratatui::crossterm::event::KeyEvent`, which is required by `KeyCombination: Into<ratatui::crossterm::event::KeyEvent>`
    |
    = help: the trait `From<ratatui::crossterm::event::KeyCode>` is implemented for `ratatui::crossterm::event::KeyEvent`
    = help: for that trait implementation, expected `ratatui::crossterm::event::KeyCode`, found `KeyCombination`
    = note: required for `KeyCombination` to implement `Into<ratatui::crossterm::event::KeyEvent>`

Some errors have detailed explanations: E0277, E0308.
```

**Comment by Julien-cpsn** [comment]
Hello guys,

this error comes from the fact that dependencies are not locked (idk why). The package crokey has been updated to support ratatui v0.28.0 which has breaking change, although I don't have ratatui v0.28.0

It will be fixed today or tomorrow with the rolling out of v0.17.0 of ATAC

Have a great day

**Comment by losinggeneration** [comment]
> this error comes from the fact that dependencies are not locked (idk why)

I would assume it has to do with how cargo handles [SemVer compatibility](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility). In this case, the version specified was `"0.27.0"` which is actually `"^0.27.0"` which means `>=0.27.0, <1.0.0` If they're introducing breaking changes in minor versions, either locking the exact version `"=0.27.0"` or using the tilde `"~0.27.0"` meaning `>=0.27.0, <0.28.0` probably makes more sense to use. I could be wrong though :shrug:

**Comment by Julien-cpsn** [comment]
> > this error comes from the fact that dependencies are not locked (idk why)
> 
> I would assume it has to do with how cargo handles [SemVer compatibility](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility). In this case, the version specified was `"0.27.0"` which is actually `"^0.27.0"` which means `>=0.27.0, <1.0.0` If they're introducing breaking changes in minor versions, either locking the exact version `"=0.27.0"` or using the tilde `"~0.27.0"` meaning `>=0.27.0, <0.28.0` probably makes more sense to use. I could be wrong though :shrug: 

Yes I started locking the dependencies

**Comment by Julien-cpsn** [comment]
Closed by https://github.com/Julien-cpsn/ATAC/releases/tag/v0.17.0
